export const LOAD_TEMPLATE_DETAIL = 'maildoodle/currentTemplate/LOAD_TEMPLATE_DETAIL';
export const LOAD_TEMPLATE_DETAIL_SUCCESS = 'maildoodle/currentTemplate/LOAD_TEMPLATE_DETAIL_SUCCESS';
export const LOAD_TEMPLATE_DETAIL_FAIL = 'maildoodle/currentTemplate/LOAD_TEMPLATE_DETAIL_FAIL';

export const UPDATE_DEVELOPMENT_VERSION = 'maildoodle/currentTemplate/UPDATE_DEVELOPMENT_VERSION';
export const UPDATE_DEVELOPMENT_VERSION_SUCCESS = 'maildoodle/currentTemplate/UPDATE_DEVELOPMENT_VERSION_SUCCESS';
export const UPDATE_DEVELOPMENT_VERSION_FAIL = 'maildoodle/currentTemplate/UPDATE_DEVELOPMENT_VERSION_FAIL';

export const PROMOTE_PRODUCTION_VERSION = 'maildoodle/currentTemplate/PROMOTE_PRODUCTION_VERSION';
export const PROMOTE_PRODUCTION_VERSION_SUCCESS = 'maildoodle/currentTemplate/PROMOTE_PRODUCTION_VERSION_SUCCESS';
export const PROMOTE_PRODUCTION_VERSION_FAIL = 'maildoodle/currentTemplate/PROMOTE_PRODUCTION_VERSION_FAIL';

export const LOAD_VERSION_FROM_HISTORY = 'maildoodle/currentTemplate/LOAD_VERSION_FROM_HISTORY';
export const LOAD_VERSION_FROM_HISTORY_SUCCESS = 'maildoodle/currentTemplate/LOAD_VERSION_FROM_HISTORY_SUCCESS';
export const LOAD_VERSION_FROM_HISTORY_FAIL = 'maildoodle/currentTemplate/LOAD_VERSION_FROM_HISTORY_FAIL';

export const CHANGE_PRODUCTION_VERSION = 'maildoodle/currentTemplate/CHANGE_PRODUCTION_VERSION';
export const CHANGE_PRODUCTION_VERSION_SUCCESS = 'maildoodle/currentTemplate/CHANGE_PRODUCTION_VERSION_SUCCESS';
export const CHANGE_PRODUCTION_VERSION_FAIL = 'maildoodle/currentTemplate/CHANGE_PRODUCTION_VERSION_FAIL';
