export const LOAD_TEMPLATE_DETAIL = 'email-templates/auth/LOAD_TEMPLATE_DETAIL';
export const LOAD_TEMPLATE_DETAIL_SUCCESS = 'email-templates/auth/LOAD_TEMPLATE_DETAIL_SUCCESS';
export const LOAD_TEMPLATE_DETAIL_FAIL = 'email-templates/auth/LOAD_TEMPLATE_DETAIL_FAIL';

export const UPDATE_DEVELOPMENT_VERSION = 'email-templates/auth/UPDATE_DEVELOPMENT_VERSION';
export const UPDATE_DEVELOPMENT_VERSION_SUCCESS = 'email-templates/auth/UPDATE_DEVELOPMENT_VERSION_SUCCESS';
export const UPDATE_DEVELOPMENT_VERSION_FAIL = 'email-templates/auth/UPDATE_DEVELOPMENT_VERSION_FAIL';

export const PROMOTE_PRODUCTION_VERSION = 'email-templates/auth/PROMOTE_PRODUCTION_VERSION';
export const PROMOTE_PRODUCTION_VERSION_SUCCESS = 'email-templates/auth/PROMOTE_PRODUCTION_VERSION_SUCCESS';
export const PROMOTE_PRODUCTION_VERSION_FAIL = 'email-templates/auth/PROMOTE_PRODUCTION_VERSION_FAIL';
